## 1. 당뇨병 데이터를 가지고 머신러닝 5가지 분류를 수행하자. 
(SVM, LR, RF, DT, KNN)
#### 1) SVM : Support Vector Machine


In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# 데이터셋 로드 (예: Pima Indians Diabetes Database 등이 있음)
# 데이터셋의 경로
data = pd.read_csv('diabetes.csv')

# 특성과 타겟 변수 분리
X = data.drop('Outcome', axis=1)  # 특성
y = data['Outcome']               # 타겟 변수

# 데이터 분할 (훈련 세트, 테스트 세트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 데이터 정규화
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# SVM 모델 생성 및 학습
model = SVC(kernel='linear')  # 'linear', 'rbf', 'poly' 등 다양한 커널 사용 가능
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 평가
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[81 18]
 [19 36]]
              precision    recall  f1-score   support

           0       0.81      0.82      0.81        99
           1       0.67      0.65      0.66        55

    accuracy                           0.76       154
   macro avg       0.74      0.74      0.74       154
weighted avg       0.76      0.76      0.76       154



#### 2) LR : Logistic Regression

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# 데이터셋의 경로를 지정
data = pd.read_csv('diabetes.csv')

# 특성과 타겟 변수 분리
X = data.drop('Outcome', axis=1)  # 특성
y = data['Outcome']               # 타겟 변수

# 데이터 분할 (훈련 세트, 테스트 세트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 데이터 정규화
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 로지스틱 회귀 모델 생성 및 학습
model = LogisticRegression()
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 평가
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[79 20]
 [18 37]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.81        99
           1       0.65      0.67      0.66        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154



#### 3) DT : Decision Tree

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# 데이터셋의 경로를 지정
data = pd.read_csv('diabetes.csv')

# 특성과 타겟 변수 분리
X = data.drop('Outcome', axis=1)  # 특성
y = data['Outcome']               # 타겟 변수

# 데이터 분할 (훈련 세트, 테스트 세트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 데이터 정규화 (선택 사항, 결정 트리에 필수는 아님)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 결정 트리 모델 생성 및 학습
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 평가
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[75 24]
 [15 40]]
              precision    recall  f1-score   support

           0       0.83      0.76      0.79        99
           1       0.62      0.73      0.67        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154



#### 4) KNN : K-최근접 이웃 알고리즘

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# 데이터셋의 경로를 지정
data = pd.read_csv('diabetes.csv')

# 특성과 타겟 변수 분리
X = data.drop('Outcome', axis=1)  # 특성
y = data['Outcome']                # 타겟 변수

# 데이터 분할 (훈련 세트, 테스트 세트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 데이터 정규화
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# KNN 모델 생성 및 학습
model = KNeighborsClassifier(n_neighbors=5)  # k 값 설정
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 평가
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[79 20]
 [27 28]]
              precision    recall  f1-score   support

           0       0.75      0.80      0.77        99
           1       0.58      0.51      0.54        55

    accuracy                           0.69       154
   macro avg       0.66      0.65      0.66       154
weighted avg       0.69      0.69      0.69       154



#### 1번 문제 정리

1. 데이터 로드: CSV 파일에서 당뇨병 데이터셋을 로드 <br>
2. 데이터 분리: 특성과 타겟 변수를 분리 <br>
3. 데이터 분할: 전체 데이터를 훈련 세트와 테스트 세트로 나누기 <br>
4. 정규화: KNN 모델은 거리 기반 알고리즘이므로, 정규화를 통해 성능을 향상 시킴 <br>
5. 모델 학습: KNN 모델을 생성하고 훈련 데이터로 학습, 여기서 n_neighbors는 K 값으로, 이 값을 조정하여 모델 성능을 최적화할 수 있음 <br>
6. 예측 및 평가: 테스트 세트에 대해 예측하고 혼동 행렬 및 분류 보고서를 출력하여 모델 성능을 평가 <br>

<br> 모든 과정은 거의 동일한 과정이라 볼 수 있지만 결정 트리의 경우 정규화가 필수는 아님. 또한 모델 학습 부분에서 KNN모델이 조금 특이한 부분이 있지만 결국 비슷한 절차로 성능을 높이려고 하는 거임.

## 2. 동일한 데이터로 딥러닝 분류 수행하기 (dense layer만 사용)


In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers

# 데이터셋 로드
data = pd.read_csv('diabetes.csv')

# 특성과 타겟 변수 분리
X = data.drop('Outcome', axis=1).values  # 특성
y = data['Outcome'].values               # 타겟 변수

# 데이터 분할 (훈련 세트, 테스트 세트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 데이터 정규화
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 모델 생성
model = keras.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)))
model.add(layers.Dense(8, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))  # 이진 분류를 위한 출력층

# 모델 컴파일
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 모델 학습
model.fit(X_train, y_train, epochs=100, batch_size=10, validation_split=0.2)

# 모델 평가
loss, accuracy = model.evaluate(X_test, y_test)
print(f'테스트 손실: {loss:.4f}, 테스트 정확도: {accuracy:.4f}')


Epoch 1/100
50/50 [==============================] - 1s 10ms/step - loss: 0.6581 - accuracy: 0.6782 - val_loss: 0.6576 - val_accuracy: 0.6829
Epoch 2/100
50/50 [==============================] - 0s 2ms/step - loss: 0.6160 - accuracy: 0.7373 - val_loss: 0.6229 - val_accuracy: 0.6992
Epoch 3/100
50/50 [==============================] - 0s 2ms/step - loss: 0.5731 - accuracy: 0.7515 - val_loss: 0.5872 - val_accuracy: 0.7154
Epoch 4/100
50/50 [==============================] - 0s 2ms/step - loss: 0.5348 - accuracy: 0.7678 - val_loss: 0.5558 - val_accuracy: 0.7236
Epoch 5/100
50/50 [==============================] - 0s 2ms/step - loss: 0.5039 - accuracy: 0.7617 - val_loss: 0.5345 - val_accuracy: 0.7398
Epoch 6/100
50/50 [==============================] - 0s 2ms/step - loss: 0.4827 - accuracy: 0.7658 - val_loss: 0.5156 - val_accuracy: 0.7480
Epoch 7/100
50/50 [==============================] - 0s 2ms/step - loss: 0.4678 - accuracy: 0.7699 - val_loss: 0.5066 - val_accuracy: 0.7317
Epoch 8/100


## 3. 해당 데이터에서 Outcome을 삭제하고 BMI를 예측하는 회귀를 수행하라.

In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers

# CSV 파일 읽기
df = pd.read_csv('diabetes.csv')

# Outcome 열 삭제
df = df.drop('Outcome', axis=1)

# 특성과 타겟 변수 분리 (BMI를 타겟으로 설정)
X = df.drop('BMI', axis=1).values  # 특성
y = df['BMI'].values               # 타겟 변수 (BMI)

# 데이터 분할 (훈련 세트, 테스트 세트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 데이터 정규화
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 모델 생성
model = keras.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)))
model.add(layers.Dense(8, activation='relu'))
model.add(layers.Dense(1))  # 회귀를 위한 출력층

# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# 모델 학습
model.fit(X_train, y_train, epochs=100, batch_size=10, validation_split=0.2)

# 모델 평가
loss, mae = model.evaluate(X_test, y_test)
print(f'테스트 손실: {loss:.4f}, 평균 절대 오차: {mae:.4f}')


Epoch 1/100
50/50 [==============================] - 1s 6ms/step - loss: 1075.3113 - mae: 31.8317 - val_loss: 1076.0687 - val_mae: 32.0346
Epoch 2/100
50/50 [==============================] - 0s 2ms/step - loss: 1024.1301 - mae: 31.0522 - val_loss: 1015.6269 - val_mae: 31.1030
Epoch 3/100
50/50 [==============================] - 0s 2ms/step - loss: 952.0605 - mae: 29.9307 - val_loss: 928.6648 - val_mae: 29.6964
Epoch 4/100
50/50 [==============================] - 0s 2ms/step - loss: 847.1238 - mae: 28.2022 - val_loss: 802.1334 - val_mae: 27.4947
Epoch 5/100
50/50 [==============================] - 0s 2ms/step - loss: 698.5999 - mae: 25.4983 - val_loss: 638.5418 - val_mae: 24.2857
Epoch 6/100
50/50 [==============================] - 0s 2ms/step - loss: 522.6838 - mae: 21.7943 - val_loss: 463.1440 - val_mae: 20.2757
Epoch 7/100
50/50 [==============================] - 0s 2ms/step - loss: 347.6447 - mae: 17.3158 - val_loss: 302.0273 - val_mae: 15.9186
Epoch 8/100
50/50 [==================

## 4. 3번과 동일하지만 dense layer만 사용한 신경만으로 회귀를 수행하라.


In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers

# CSV 파일 읽기
df = pd.read_csv('diabetes.csv')

# Outcome 열 삭제
df = df.drop('Outcome', axis=1)

# 특성과 타겟 변수 분리 (BMI를 타겟으로 설정)
X = df.drop('BMI', axis=1).values  # 특성
y = df['BMI'].values               # 타겟 변수 (BMI)

# 데이터 분할 (훈련 세트, 테스트 세트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 데이터 정규화
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 모델 생성
model = keras.Sequential()
model.add(layers.Dense(32, activation='relu', input_shape=(X_train.shape[1],)))    # 첫 번째 Dense 레이어
model.add(layers.Dense(16, activation='relu'))                                     # 두 번째 Dense 레이어
model.add(layers.Dense(1))                                                         # 회귀를 위한 출력층

# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# 모델 학습
model.fit(X_train, y_train, epochs=100, batch_size=10, validation_split=0.2)

# 모델 평가
loss, mae = model.evaluate(X_test, y_test)
print(f'테스트 손실: {loss:.4f}, 평균 절대 오차: {mae:.4f}')


Epoch 1/100
50/50 [==============================] - 1s 6ms/step - loss: 1040.0756 - mae: 31.2840 - val_loss: 1019.1340 - val_mae: 31.1403
Epoch 2/100
50/50 [==============================] - 0s 2ms/step - loss: 943.0643 - mae: 29.7568 - val_loss: 891.9924 - val_mae: 29.0479
Epoch 3/100
50/50 [==============================] - 0s 2ms/step - loss: 783.7164 - mae: 27.0211 - val_loss: 692.4353 - val_mae: 25.3716
Epoch 4/100
50/50 [==============================] - 0s 2ms/step - loss: 557.8641 - mae: 22.5264 - val_loss: 441.9905 - val_mae: 19.7602
Epoch 5/100
50/50 [==============================] - 0s 2ms/step - loss: 315.7254 - mae: 16.2261 - val_loss: 218.9198 - val_mae: 12.9334
Epoch 6/100
50/50 [==============================] - 0s 2ms/step - loss: 148.2256 - mae: 10.2821 - val_loss: 104.3747 - val_mae: 8.2836
Epoch 7/100
50/50 [==============================] - 0s 2ms/step - loss: 89.5787 - mae: 7.2216 - val_loss: 78.0490 - val_mae: 6.9590
Epoch 8/100
50/50 [=========================